In [1]:
import pandas as pd
from datetime import datetime
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns; sns.set()
import warnings
warnings.filterwarnings('ignore')
from matplotlib import cm
import os

In [2]:
df = pd.read_excel('MasterData_Wilson.xlsx')

In [3]:
df.shape

(468883, 31)

In [4]:
df.head(20)

date                 time    year  MonthN Month  WeekN   Day WeekD  \
0  2016-07-25  2016-07-25 09:04:00  2016.0     7.0   Jul   31.0  25.0   Mon   
1  2016-07-25  2016-07-25 09:28:00  2016.0     7.0   Jul   31.0  25.0   Mon   
2  2016-07-25  2016-07-25 09:28:00  2016.0     7.0   Jul   31.0  25.0   Mon   
3  2016-07-25  2016-07-25 09:28:00  2016.0     7.0   Jul   31.0  25.0   Mon   
4  2016-07-25  2016-07-25 09:29:00  2016.0     7.0   Jul   31.0  25.0   Mon   
5  2016-07-25  2016-07-25 09:42:00  2016.0     7.0   Jul   31.0  25.0   Mon   
6  2016-07-25  2016-07-25 10:00:00  2016.0     7.0   Jul   31.0  25.0   Mon   
7  2016-07-25  2016-07-25 10:01:00  2016.0     7.0   Jul   31.0  25.0   Mon   
8  2016-07-25  2016-07-25 10:01:00  2016.0     7.0   Jul   31.0  25.0   Mon   
9  2016-07-25  2016-07-25 10:02:00  2016.0     7.0   Jul   31.0  25.0   Mon   
10 2016-07-25  2016-07-25 10:02:00  2016.0     7.0   Jul   31.0  25.0   Mon   
11 2016-07-25  2016-07-25 10:11:00  2016.0     7.0   Jul   31.0  25.0   Mon   
12 2016-07-25  2016-07-25 10:16:00  2016.0     7.0   Jul   31.0  25.0   Mon   
13 2016-07-25  2016-07-25 10:16:00  2016.0     7.0   Jul   31.0  25.0   Mon   
14 2016-07-25  2016-07-25 10:16:00  2016.0     7.0   Jul   31.0  25.0   Mon   
15 2016-07-25  2016-07-25 10:32:00  2016.0     7.0   Jul   31.0  25.0   Mon   
16 2016-07-25  2016-07-25 10:32:00  2016.0     7.0   Jul   31.0  25.0   Mon   
17 2016-07-25  2016-07-25 11:04:00  2016.0     7.0   Jul   31.0  25.0   Mon   
18 2016-07-25  2016-07-25 11:04:00  2016.0     7.0   Jul   31.0  25.0   Mon   
19 2016-07-25  2016-07-25 11:20:00  2016.0     7.0   Jul   31.0  25.0   Mon   

       H   Min     ...      Price Quantity Modifiers  Subtotal Discounts  \
0    9.0   4.0     ...       2.25        1         0      2.25         0   
1    9.0  28.0     ...          2        2         0         4         0   
2    9.0  28.0     ...       3.75        1         0      3.75         0   
3    9.0  28.0     ...        3.8        1         0       3.8         0   
4    9.0  29.0     ...        3.5        1         0       3.5         0   
5    9.0  42.0     ...        3.8        1         0       3.8         0   
6   10.0   0.0     ...          4        3         0        12         0   
7   10.0   1.0     ...        3.8        1         0       3.8         0   
8   10.0   1.0     ...        4.5        1         0       4.5         0   
9   10.0   2.0     ...          4        1         0         4         0   
10  10.0   2.0     ...        2.5        1         0       2.5         0   
11  10.0  11.0     ...        3.8        1         0       3.8         0   
12  10.0  16.0     ...        2.5        1         0       2.5         0   
13  10.0  16.0     ...        3.5        2         0         7         0   
14  10.0  16.0     ...        3.8        2         0       7.6         0   
15  10.0  32.0     ...        4.5        1         0       4.5         0   
16  10.0  32.0     ...       3.75        1         0      3.75         0   
17  11.0   4.0     ...        3.5        1         0       3.5         0   
18  11.0   4.0     ...        2.5        1         0       2.5         0   
19  11.0  20.0     ...          4        2         0         8         0   

   Net Total   Tax Total Due Unnamed: 29 Unnamed: 30  
0       2.25  0.05       2.3         NaN         NaN  
1          4  0.09      4.09         NaN         NaN  
2       3.75  0.38      4.13         NaN         NaN  
3        3.8  0.09      3.89         NaN         NaN  
4        3.5  0.08      3.58         NaN         NaN  
5        3.8  0.09      3.89         NaN         NaN  
6         12  0.27     12.27         NaN         NaN  
7        3.8  0.09      3.89         NaN         NaN  
8        4.5   0.1       4.6         NaN         NaN  
9          4  0.41      4.41         NaN         NaN  
10       2.5  0.26      2.76         NaN         NaN  
11       3.8  0.39      4.19         NaN         NaN  
12       2.5  0.26      2.76         

In [5]:
df=df.drop(columns=['Unnamed: 29','Unnamed: 30'])
list(df.columns)

['date',
 'time',
 'year',
 'MonthN',
 'Month',
 'WeekN',
 'Day',
 'WeekD',
 'H',
 'Min',
 '30min',
 'Rtime',
 '30time',
 'H.5',
 'Operation',
 'Line Item',
 'Department',
 'Category',
 'Supplier',
 'Supplier Code',
 'Cost',
 'Price',
 'Quantity',
 'Modifiers',
 'Subtotal',
 'Discounts',
 'Net Total',
 'Tax',
 'Total Due']

In [6]:
# df['Price'].dtype
df.dtypes


date             datetime64[ns]
time                     object
year                    float64
MonthN                  float64
Month                    object
WeekN                   float64
Day                     float64
WeekD                    object
H                       float64
Min                     float64
30min                   float64
Rtime                    object
30time                   object
H.5                     float64
Operation                object
Line Item                object
Department               object
Category                 object
Supplier                 object
Supplier Code            object
Cost                     object
Price                    object
Quantity                 object
Modifiers                object
Subtotal                 object
Discounts                object
Net Total                object
Tax                      object
Total Due                object
dtype: object

In [7]:
# df["Net Total"] = pd.to_numeric(df["Net Total"])
# df.dtypes


df.drop(df.index[430502:435254], inplace=True)


In [8]:
df=df.drop(columns=['Supplier Code','Modifiers', 'Subtotal', 'Discounts', 'Tax', 'Operation'])
list(df.columns)

['date',
 'time',
 'year',
 'MonthN',
 'Month',
 'WeekN',
 'Day',
 'WeekD',
 'H',
 'Min',
 '30min',
 'Rtime',
 '30time',
 'H.5',
 'Line Item',
 'Department',
 'Category',
 'Supplier',
 'Cost',
 'Price',
 'Quantity',
 'Net Total',
 'Total Due']

In [9]:
df["Net Total"] = pd.to_numeric(df["Net Total"])
df.dtypes



date          datetime64[ns]
time                  object
year                 float64
MonthN               float64
Month                 object
WeekN                float64
Day                  float64
WeekD                 object
H                    float64
Min                  float64
30min                float64
Rtime                 object
30time                object
H.5                  float64
Line Item             object
Department            object
Category              object
Supplier              object
Cost                  object
Price                 object
Quantity              object
Net Total            float64
Total Due             object
dtype: object

In [10]:
df.shape

(464131, 23)

In [11]:
df.describe()

year         MonthN          WeekN            Day  \
count  464130.000000  464130.000000  464130.000000  464130.000000   
mean     2017.220531       6.930789      28.764092      15.477698   
std         0.716370       3.300020      14.406295       8.677825   
min      2016.000000       1.000000       1.000000       1.000000   
25%      2017.000000       4.000000      17.000000       8.000000   
50%      2017.000000       7.000000      31.000000      15.000000   
75%      2018.000000      10.000000      41.000000      23.000000   
max      2018.000000      12.000000      53.000000      31.000000   

                   H            Min          30min            H.5  \
count  464130.000000  464130.000000  464130.000000  464131.000000   
mean       12.106214      29.644669      14.896775      12.354467   
std         3.115303      17.302388      14.999661       3.106605   
min         1.000000       0.000000       0.000000       0.000000   
25%        10.000000      15.000000       0.000000      10.000000   
50%        12.000000      30.000000       0.000000      12.000000   
75%        15.000000      45.000000      30.000000      15.000000   
max        23.000000      59.000000      30.000000      23.500000   

           Net Total  
count  464131.000000  
mean        4.705988  
std         3.878319  
min      -127.500000  
25%         2.500000  
50%         3.750000  
75%         5.800000  
max       313.200000

In [12]:
df.isnull().sum() 


date          0
time          1
year          1
MonthN        1
Month         1
WeekN         1
Day           1
WeekD         1
H             1
Min           1
30min         1
Rtime         1
30time        1
H.5           0
Line Item     1
Department    1
Category      1
Supplier      1
Cost          0
Price         0
Quantity      0
Net Total     0
Total Due     0
dtype: int64

In [13]:
df = df.dropna(how='any') 

In [14]:
df.shape

(464130, 23)

In [15]:
df.count()

date          464130
time          464130
year          464130
MonthN        464130
Month         464130
WeekN         464130
Day           464130
WeekD         464130
H             464130
Min           464130
30min         464130
Rtime         464130
30time        464130
H.5           464130
Line Item     464130
Department    464130
Category      464130
Supplier      464130
Cost          464130
Price         464130
Quantity      464130
Net Total     464130
Total Due     464130
dtype: int64

In [16]:
df.dtypes



date          datetime64[ns]
time                  object
year                 float64
MonthN               float64
Month                 object
WeekN                float64
Day                  float64
WeekD                 object
H                    float64
Min                  float64
30min                float64
Rtime                 object
30time                object
H.5                  float64
Line Item             object
Department            object
Category              object
Supplier              object
Cost                  object
Price                 object
Quantity              object
Net Total            float64
Total Due             object
dtype: object

In [18]:
# df=df.drop(columns=['Month','Modifiers', 'Subtotal', 'Discounts', 'Tax', 'Operation'])
list(df.columns)

['date',
 'time',
 'year',
 'MonthN',
 'Month',
 'WeekN',
 'Day',
 'WeekD',
 'H',
 'Min',
 '30min',
 'Rtime',
 '30time',
 'H.5',
 'Line Item',
 'Department',
 'Category',
 'Supplier',
 'Cost',
 'Price',
 'Quantity',
 'Net Total',
 'Total Due']

In [19]:
df["Total Due"] = pd.to_numeric(df["Total Due"])
df["Cost"] = pd.to_numeric(df["Cost"])
df["Price"] = pd.to_numeric(df["Price"])
df["Quantity"] = pd.to_numeric(df["Quantity"])


df.dtypes

date          datetime64[ns]
time                  object
year                 float64
MonthN               float64
Month                 object
WeekN                float64
Day                  float64
WeekD                 object
H                    float64
Min                  float64
30min                float64
Rtime                 object
30time                object
H.5                  float64
Line Item             object
Department            object
Category              object
Supplier              object
Cost                 float64
Price                float64
Quantity               int64
Net Total            float64
Total Due            float64
dtype: object

In [104]:
# df['H']=pd.to_datetime(df['H'])


In [105]:
# df['H']=df['H'].dt.hour


In [20]:
def hourly(x):
    if x['H']==7:
        return '07-7am to 8am'
    elif x['H']==8:
        return '08-8am to 9am'
    elif x['H']==9:
        return '09-9am to 10am'
    elif x['H']==10:
        return '10-10am to 11am'
    elif x['H']==11:
        return '11-11am to 12pm'
    elif x['H']==12:
        return '12-12pm to 1pm'
    elif x['H']==13:
        return '13-1pm to 2pm'
    elif x['H']==14:
        return '14-2pm to 3pm'
    elif x['H']==15:
        return '15-3pm to 4pm'
    elif x['H']==16:
        return '16-4pm to 5pm'
    elif x['H']==17:
        return '17-5pm to 6pm'
    elif x['H']==18:
        return '18-6pm to 7pm'
    else:
        return '19-7pm to 8pm'


In [21]:
df['H']=df.apply(hourly,axis=1)


In [24]:
df.head()

date                 time    year  MonthN Month  WeekN   Day WeekD  \
0 2016-07-25  2016-07-25 09:04:00  2016.0     7.0   Jul   31.0  25.0   Mon   
1 2016-07-25  2016-07-25 09:28:00  2016.0     7.0   Jul   31.0  25.0   Mon   
2 2016-07-25  2016-07-25 09:28:00  2016.0     7.0   Jul   31.0  25.0   Mon   
3 2016-07-25  2016-07-25 09:28:00  2016.0     7.0   Jul   31.0  25.0   Mon   
4 2016-07-25  2016-07-25 09:29:00  2016.0     7.0   Jul   31.0  25.0   Mon   

                H   Min     ...                        Line Item  Department  \
0  09-9am to 10am   4.0     ...                Macaron Chocolate      Pastry   
1  09-9am to 10am  28.0     ...                          Type in     general   
2  09-9am to 10am  28.0     ...                            Latte      Coffee   
3  09-9am to 10am  28.0     ...      Chocolate croissant (to go)  Croissants   
4  09-9am to 10am  29.0     ...               Baguette tradition       Bread   

  Category                  Supplier Cost Price Quantity Net Total  Total Due  \
0  general               Cook Au Vin  1.0  2.25        1      2.25       2.30   
1  general               not tracked  0.0  2.00        2      4.00       4.09   
2  general  Chicago Beverage Company  0.0  3.75        1      3.75       4.13   
3    To Go               Cook Au Vin  0.0  3.80        1      3.80       3.89   
4  general               Cook Au Vin  1.4  3.50        1      3.50       3.58   

     DAY_PART  
0  01-Morning  
1  01-Morning  
2  01-Morning  
3  01-Morning  
4  01-Morning  

[5 rows x 24 columns]

In [25]:
def daypart(x):
    if (
        x['H']=='07-7am to 8am'
    or
        x['H']=='07-7am to 8am'
    or
        x['H']=='08-8am to 9am'
    or
        x['H']=='09-9am to 10am'
    or
        x['H']=='10-10am to 11am'
    or 
        x['H']=='11-11am to 12pm'):
        
        return '01-Morning'

    elif ( 
        x['H']=='12-12pm to 1pm'
    or
        x['H']=='13-1pm to 2pm'
    or
        x['H']=='14-2pm to 3pm'
    or
        x['H']=='15-3pm to 4pm'):
        
        return '02-Afternoon'
    
    elif (    
        x['H']=='16-4pm to 5pm'
    or 
        x['H']=='17-5pm to 6pm'):
        
        return '03-Early Evening'
    
    else:
        return '04-Evening'


In [26]:
df['DAY_PART']=df.apply(daypart,axis=1)


In [27]:
df.head()

date                 time    year  MonthN Month  WeekN   Day WeekD  \
0 2016-07-25  2016-07-25 09:04:00  2016.0     7.0   Jul   31.0  25.0   Mon   
1 2016-07-25  2016-07-25 09:28:00  2016.0     7.0   Jul   31.0  25.0   Mon   
2 2016-07-25  2016-07-25 09:28:00  2016.0     7.0   Jul   31.0  25.0   Mon   
3 2016-07-25  2016-07-25 09:28:00  2016.0     7.0   Jul   31.0  25.0   Mon   
4 2016-07-25  2016-07-25 09:29:00  2016.0     7.0   Jul   31.0  25.0   Mon   

                H   Min     ...                        Line Item  Department  \
0  09-9am to 10am   4.0     ...                Macaron Chocolate      Pastry   
1  09-9am to 10am  28.0     ...                          Type in     general   
2  09-9am to 10am  28.0     ...                            Latte      Coffee   
3  09-9am to 10am  28.0     ...      Chocolate croissant (to go)  Croissants   
4  09-9am to 10am  29.0     ...               Baguette tradition       Bread   

  Category                  Supplier Cost Price Quantity Net Total  Total Due  \
0  general               Cook Au Vin  1.0  2.25        1      2.25       2.30   
1  general               not tracked  0.0  2.00        2      4.00       4.09   
2  general  Chicago Beverage Company  0.0  3.75        1      3.75       4.13   
3    To Go               Cook Au Vin  0.0  3.80        1      3.80       3.89   
4  general               Cook Au Vin  1.4  3.50        1      3.50       3.58   

     DAY_PART  
0  01-Morning  
1  01-Morning  
2  01-Morning  
3  01-Morning  
4  01-Morning  

[5 rows x 24 columns]

In [28]:
def seasonal(x):
    
    if (
        x['MonthN']==12.0
    or 
        x['MonthN']==11.0
    or
        x['MonthN']==1.0
    or
        x['MonthN']==2.0):
        
        return 'Cold Season'
    
    elif (
        x['MonthN']==3.0
    or 
        x['MonthN']==4.0
    or
        x['MonthN']==5.0
    or
        x['MonthN']==9.0
    or 
        x['MonthN']==10.0):
        
        return 'Cool Season'
    
    else:
        return 'Hot Season'

In [29]:
df['SEASONAL']=df.apply(seasonal,axis=1)


In [30]:
df.head()

date                 time    year  MonthN Month  WeekN   Day WeekD  \
0 2016-07-25  2016-07-25 09:04:00  2016.0     7.0   Jul   31.0  25.0   Mon   
1 2016-07-25  2016-07-25 09:28:00  2016.0     7.0   Jul   31.0  25.0   Mon   
2 2016-07-25  2016-07-25 09:28:00  2016.0     7.0   Jul   31.0  25.0   Mon   
3 2016-07-25  2016-07-25 09:28:00  2016.0     7.0   Jul   31.0  25.0   Mon   
4 2016-07-25  2016-07-25 09:29:00  2016.0     7.0   Jul   31.0  25.0   Mon   

                H   Min     ...      Department Category  \
0  09-9am to 10am   4.0     ...          Pastry  general   
1  09-9am to 10am  28.0     ...         general  general   
2  09-9am to 10am  28.0     ...          Coffee  general   
3  09-9am to 10am  28.0     ...      Croissants    To Go   
4  09-9am to 10am  29.0     ...           Bread  general   

                   Supplier  Cost Price Quantity Net Total Total Due  \
0               Cook Au Vin   1.0  2.25        1      2.25      2.30   
1               not tracked   0.0  2.00        2      4.00      4.09   
2  Chicago Beverage Company   0.0  3.75        1      3.75      4.13   
3               Cook Au Vin   0.0  3.80        1      3.80      3.89   
4               Cook Au Vin   1.4  3.50        1      3.50      3.58   

     DAY_PART    SEASONAL  
0  01-Morning  Hot Season  
1  01-Morning  Hot Season  
2  01-Morning  Hot Season  
3  01-Morning  Hot Season  
4  01-Morning  Hot Season  

[5 rows x 25 columns]

In [33]:
# df.to_excel("MasterData2.xlsx", index=False, header=True)

In [72]:
df['Net Total'].describe()


count    24828.000000
mean        87.973048
std        121.053018
min         -2.000000
25%         13.750000
50%         39.000000
75%        117.900000
max       1901.420000
Name: Net Total, dtype: float64

In [34]:
# seasonal_volume=df.groupby(['SEASONAL','MonthN', 'DAY_PART','H','WeekD'],as_index=False).agg({'Total Sales':'sum'})
                               
                             
                    

In [ ]:
# seasonal_volume=actual_sales.groupby(['SEASONAL'
#                                 ,'BUSINESS_DATE'
#                                 ,'STORE_ID'
#                                 ,'YEAR'
#                                 ,'MONTH'
#                                 ,'DAYOFWEEK'
#                                 ,'DAY_PART'
#                                 ,'HOURLY'],as_index=False).agg({'TICKET_NUM':'count'
#                                                                 ,'TOTAL_SALES_AMOUNT':'sum'
#                                                                 ,'HOP_OUT_TIME':'mean'
#                                                                 })

In [ ]:
# date_group = file.groupby(['date'])['Total Due'].sum().to_frame(name = 'count').reset_index()
# file1 = file.merge(date_group)
# file1.head()

In [40]:
df['Department'].value_counts()

Croissants      114208
Coffee           87886
Pastry           67933
Hot Food         61117
Bread            57392
Dry Pastries     24053
Retail           20795
Cold Drinks      20405
general           3808
Sandwiches        3697
Type in           2143
Bakery             471
Gift Card          222
Name: Department, dtype: int64

In [42]:
df=df.drop(columns=['Min','30min', 'Rtime', '30time', 'H.5'])
list(df.columns)

['date',
 'time',
 'year',
 'MonthN',
 'Month',
 'WeekN',
 'Day',
 'WeekD',
 'H',
 'Line Item',
 'Department',
 'Category',
 'Supplier',
 'Cost',
 'Price',
 'Quantity',
 'Net Total',
 'Total Due',
 'DAY_PART',
 'SEASONAL']

In [43]:
df=df.drop(columns=['Price','WeekN', 'H', 'Supplier', 'Category'])

list(df.columns)

['date',
 'time',
 'year',
 'MonthN',
 'Month',
 'Day',
 'WeekD',
 'Line Item',
 'Department',
 'Cost',
 'Quantity',
 'Net Total',
 'Total Due',
 'DAY_PART',
 'SEASONAL']

In [45]:
df=df.drop(columns=['Day'])


df.head()

date                 time    year  MonthN Month WeekD  \
0 2016-07-25  2016-07-25 09:04:00  2016.0     7.0   Jul   Mon   
1 2016-07-25  2016-07-25 09:28:00  2016.0     7.0   Jul   Mon   
2 2016-07-25  2016-07-25 09:28:00  2016.0     7.0   Jul   Mon   
3 2016-07-25  2016-07-25 09:28:00  2016.0     7.0   Jul   Mon   
4 2016-07-25  2016-07-25 09:29:00  2016.0     7.0   Jul   Mon   

                     Line Item  Department  Cost  Quantity  Net Total  \
0            Macaron Chocolate      Pastry   1.0         1       2.25   
1                      Type in     general   0.0         2       4.00   
2                        Latte      Coffee   0.0         1       3.75   
3  Chocolate croissant (to go)  Croissants   0.0         1       3.80   
4           Baguette tradition       Bread   1.4         1       3.50   

   Total Due    DAY_PART    SEASONAL  
0       2.30  01-Morning  Hot Season  
1       4.09  01-Morning  Hot Season  
2       4.13  01-Morning  Hot Season  
3       3.89  01-Morning  Hot Season  
4       3.58  01-Morning  Hot Season

In [46]:
df=df.drop(columns=['Month', 'time'])


df.head()

date    year  MonthN WeekD                    Line Item  Department  \
0 2016-07-25  2016.0     7.0   Mon            Macaron Chocolate      Pastry   
1 2016-07-25  2016.0     7.0   Mon                      Type in     general   
2 2016-07-25  2016.0     7.0   Mon                        Latte      Coffee   
3 2016-07-25  2016.0     7.0   Mon  Chocolate croissant (to go)  Croissants   
4 2016-07-25  2016.0     7.0   Mon           Baguette tradition       Bread   

   Cost  Quantity  Net Total  Total Due    DAY_PART    SEASONAL  
0   1.0         1       2.25       2.30  01-Morning  Hot Season  
1   0.0         2       4.00       4.09  01-Morning  Hot Season  
2   0.0         1       3.75       4.13  01-Morning  Hot Season  
3   0.0         1       3.80       3.89  01-Morning  Hot Season  
4   1.4         1       3.50       3.58  01-Morning  Hot Season

In [48]:
df.to_csv("MasterData2.csv", index=False, header=True)

In [49]:
df = pd.read_csv('MasterData2.csv')

In [50]:
df.head()

date    year  MonthN WeekD                    Line Item  Department  \
0  2016-07-25  2016.0     7.0   Mon            Macaron Chocolate      Pastry   
1  2016-07-25  2016.0     7.0   Mon                      Type in     general   
2  2016-07-25  2016.0     7.0   Mon                        Latte      Coffee   
3  2016-07-25  2016.0     7.0   Mon  Chocolate croissant (to go)  Croissants   
4  2016-07-25  2016.0     7.0   Mon           Baguette tradition       Bread   

   Cost  Quantity  Net Total  Total Due    DAY_PART    SEASONAL  
0   1.0         1       2.25       2.30  01-Morning  Hot Season  
1   0.0         2       4.00       4.09  01-Morning  Hot Season  
2   0.0         1       3.75       4.13  01-Morning  Hot Season  
3   0.0         1       3.80       3.89  01-Morning  Hot Season  
4   1.4         1       3.50       3.58  01-Morning  Hot Season

In [57]:
# seasonal_volume=df.groupby(['Department',
#                             'date',
#                             'year',
#                             'MonthN',
#                             'WeekD',
#                             'SEASONAL',
#                             'DAY_PART'],as_index=False).agg({
#                                                             'Net Total':'sum'})

In [63]:
seasonal_volume1=df.groupby(['Department',
                            'date',
                            'year',
                            'MonthN',
                            'WeekD',
                            'SEASONAL',
                            'DAY_PART'],as_index=False).agg({
                                                            'Quantity':'count',
                                                            'Net Total':'sum'})

In [65]:
seasonal_volume1.head(20)

Department        date    year  MonthN WeekD    SEASONAL          DAY_PART  \
0      Bakery  2016-07-27  2016.0     7.0   Wed  Hot Season      02-Afternoon   
1      Bakery  2016-07-27  2016.0     7.0   Wed  Hot Season        04-Evening   
2      Bakery  2016-07-28  2016.0     7.0   Thu  Hot Season        01-Morning   
3      Bakery  2016-07-28  2016.0     7.0   Thu  Hot Season      02-Afternoon   
4      Bakery  2016-07-28  2016.0     7.0   Thu  Hot Season  03-Early Evening   
5      Bakery  2016-07-28  2016.0     7.0   Thu  Hot Season        04-Evening   
6      Bakery  2016-07-29  2016.0     7.0   Fri  Hot Season        01-Morning   
7      Bakery  2016-07-29  2016.0     7.0   Fri  Hot Season      02-Afternoon   
8      Bakery  2016-07-29  2016.0     7.0   Fri  Hot Season  03-Early Evening   
9      Bakery  2016-07-30  2016.0     7.0   Sat  Hot Season        01-Morning   
10     Bakery  2016-07-30  2016.0     7.0   Sat  Hot Season      02-Afternoon   
11     Bakery  2016-07-30  2016.0     7.0   Sat  Hot Season  03-Early Evening   
12     Bakery  2016-07-31  2016.0     7.0   Sun  Hot Season        01-Morning   
13     Bakery  2016-07-31  2016.0     7.0   Sun  Hot Season      02-Afternoon   
14     Bakery  2016-08-02  2016.0     8.0   Tue  Hot Season        01-Morning   
15     Bakery  2016-08-02  2016.0     8.0   Tue  Hot Season      02-Afternoon   
16     Bakery  2016-08-02  2016.0     8.0   Tue  Hot Season        04-Evening   
17     Bakery  2016-08-03  2016.0     8.0   Wed  Hot Season        01-Morning   
18     Bakery  2016-08-03  2016.0     8.0   Wed  Hot Season      02-Afternoon   
19     Bakery  2016-08-03  2016.0     8.0   Wed  Hot Season  03-Early Evening   

    Quantity  Net Total  
0          1        2.0  
1          2       12.0  
2          2        4.0  
3          4       10.0  
4          2        8.0  
5          1        4.0  
6          4        8.0  
7         12       39.0  
8          4       13.0  
9          4       19.0  
10         3       14.0  
11         4       24.0  
12         6       26.5  
13         1        5.0  
14         2       11.5  
15         4       15.0  
16         1        2.5  
17         1        2.5  
18         1        2.5  
19         1        2.0

In [62]:
df.dtypes

date           object
year          float64
MonthN        float64
WeekD          object
Line Item      object
Department     object
Cost          float64
Quantity        int64
Net Total     float64
Total Due     float64
DAY_PART       object
SEASONAL       object
dtype: object

In [66]:
seasonal_volume1['Avg Sale per Product']=seasonal_volume1['Net Total']/seasonal_volume1['Quantity']


In [67]:
seasonal_volume1.head()

Department        date    year  MonthN WeekD    SEASONAL          DAY_PART  \
0     Bakery  2016-07-27  2016.0     7.0   Wed  Hot Season      02-Afternoon   
1     Bakery  2016-07-27  2016.0     7.0   Wed  Hot Season        04-Evening   
2     Bakery  2016-07-28  2016.0     7.0   Thu  Hot Season        01-Morning   
3     Bakery  2016-07-28  2016.0     7.0   Thu  Hot Season      02-Afternoon   
4     Bakery  2016-07-28  2016.0     7.0   Thu  Hot Season  03-Early Evening   

   Quantity  Net Total  Avg Sale per Product  
0         1        2.0                   2.0  
1         2       12.0                   6.0  
2         2        4.0                   2.0  
3         4       10.0                   2.5  
4         2        8.0                   4.0

In [68]:
seasonal_volume1.to_csv("SeasonalVolume.csv", index=False, header=True)

In [69]:
df = pd.read_csv('SeasonalVolume.csv')

In [70]:
df.head()

Department        date    year  MonthN WeekD    SEASONAL          DAY_PART  \
0     Bakery  2016-07-27  2016.0     7.0   Wed  Hot Season      02-Afternoon   
1     Bakery  2016-07-27  2016.0     7.0   Wed  Hot Season        04-Evening   
2     Bakery  2016-07-28  2016.0     7.0   Thu  Hot Season        01-Morning   
3     Bakery  2016-07-28  2016.0     7.0   Thu  Hot Season      02-Afternoon   
4     Bakery  2016-07-28  2016.0     7.0   Thu  Hot Season  03-Early Evening   

   Quantity  Net Total  Avg Sale per Product  
0         1        2.0                   2.0  
1         2       12.0                   6.0  
2         2        4.0                   2.0  
3         4       10.0                   2.5  
4         2        8.0                   4.0

In [83]:
# RANDOM FOREST STARTS HERE 
df=df.drop(columns=['date'])


df.head()

Department    year  MonthN WeekD    SEASONAL          DAY_PART  Quantity  \
0     Bakery  2016.0     7.0   Wed  Hot Season      02-Afternoon         1   
1     Bakery  2016.0     7.0   Wed  Hot Season        04-Evening         2   
2     Bakery  2016.0     7.0   Thu  Hot Season        01-Morning         2   
3     Bakery  2016.0     7.0   Thu  Hot Season      02-Afternoon         4   
4     Bakery  2016.0     7.0   Thu  Hot Season  03-Early Evening         2   

   Net Total  Avg Sale per Product  
0        2.0                   2.0  
1       12.0                   6.0  
2        4.0                   2.0  
3       10.0                   2.5  
4        8.0                   4.0

In [84]:
DF_dummies = pd.get_dummies(df)

In [85]:
DF_dummies.head(5)

year  MonthN  Quantity  Net Total  Avg Sale per Product  \
0  2016.0     7.0         1        2.0                   2.0   
1  2016.0     7.0         2       12.0                   6.0   
2  2016.0     7.0         2        4.0                   2.0   
3  2016.0     7.0         4       10.0                   2.5   
4  2016.0     7.0         2        8.0                   4.0   

   Department_Bakery  Department_Bread  Department_Coffee  \
0                  1                 0                  0   
1                  1                 0                  0   
2                  1                 0                  0   
3                  1                 0                  0   
4                  1                 0                  0   

   Department_Cold Drinks  Department_Croissants         ...           \
0                       0                      0         ...            
1                       0                      0         ...            
2                       0                      0         ...            
3                       0                      0         ...            
4                       0                      0         ...            

   WeekD_Thu  WeekD_Tue  WeekD_Wed  SEASONAL_Cold Season  \
0          0          0          1                     0   
1          0          0          1                     0   
2          1          0          0                     0   
3          1          0          0                     0   
4          1          0          0                     0   

   SEASONAL_Cool Season  SEASONAL_Hot Season  DAY_PART_01-Morning  \
0                     0                    1                    0   
1                     0                    1                    0   
2                     0                    1                    1   
3                     0                    1                    0   
4                     0                    1                    0   

   DAY_PART_02-Afternoon  DAY_PART_03-Early Evening  DAY_PART_04-Evening  
0                      1                          0                    0  
1                      0                          0                    1  
2                      0                          0                    0  
3                      1                          0                    0  
4                      0                          1                    0  

[5 rows x 32 columns]

In [86]:
DF_data = DF_dummies.reset_index(drop=True)


In [87]:
list(DF_data.columns)

['year',
 'MonthN',
 'Quantity',
 'Net Total',
 'Avg Sale per Product',
 'Department_Bakery',
 'Department_Bread',
 'Department_Coffee',
 'Department_Cold Drinks',
 'Department_Croissants',
 'Department_Dry Pastries',
 'Department_Gift Card',
 'Department_Hot Food',
 'Department_Pastry',
 'Department_Retail',
 'Department_Sandwiches',
 'Department_Type in',
 'Department_general',
 'WeekD_Fri',
 'WeekD_Mon',
 'WeekD_Sat',
 'WeekD_Sun',
 'WeekD_Thu',
 'WeekD_Tue',
 'WeekD_Wed',
 'SEASONAL_Cold Season',
 'SEASONAL_Cool Season',
 'SEASONAL_Hot Season',
 'DAY_PART_01-Morning',
 'DAY_PART_02-Afternoon',
 'DAY_PART_03-Early Evening',
 'DAY_PART_04-Evening']

In [88]:
DF_data = DF_data[['Net Total',
                   'year',
 'MonthN',
 'Quantity',
 'Avg Sale per Product',
 'Department_Bakery',
 'Department_Bread',
 'Department_Coffee',
 'Department_Cold Drinks',
 'Department_Croissants',
 'Department_Dry Pastries',
 'Department_Gift Card',
 'Department_Hot Food',
 'Department_Pastry',
 'Department_Retail',
 'Department_Sandwiches',
 'Department_Type in',
 'Department_general',
 'WeekD_Fri',
 'WeekD_Mon',
 'WeekD_Sat',
 'WeekD_Sun',
 'WeekD_Thu',
 'WeekD_Tue',
 'WeekD_Wed',
 'SEASONAL_Cold Season',
 'SEASONAL_Cool Season',
 'SEASONAL_Hot Season',
 'DAY_PART_01-Morning',
 'DAY_PART_02-Afternoon',
 'DAY_PART_03-Early Evening',
 'DAY_PART_04-Evening']]

In [89]:
DF_data.head(5)

Net Total    year  MonthN  Quantity  Avg Sale per Product  \
0        2.0  2016.0     7.0         1                   2.0   
1       12.0  2016.0     7.0         2                   6.0   
2        4.0  2016.0     7.0         2                   2.0   
3       10.0  2016.0     7.0         4                   2.5   
4        8.0  2016.0     7.0         2                   4.0   

   Department_Bakery  Department_Bread  Department_Coffee  \
0                  1                 0                  0   
1                  1                 0                  0   
2                  1                 0                  0   
3                  1                 0                  0   
4                  1                 0                  0   

   Department_Cold Drinks  Department_Croissants         ...           \
0                       0                      0         ...            
1                       0                      0         ...            
2                       0                      0         ...            
3                       0                      0         ...            
4                       0                      0         ...            

   WeekD_Thu  WeekD_Tue  WeekD_Wed  SEASONAL_Cold Season  \
0          0          0          1                     0   
1          0          0          1                     0   
2          1          0          0                     0   
3          1          0          0                     0   
4          1          0          0                     0   

   SEASONAL_Cool Season  SEASONAL_Hot Season  DAY_PART_01-Morning  \
0                     0                    1                    0   
1                     0                    1                    0   
2                     0                    1                    1   
3                     0                    1                    0   
4                     0                    1                    0   

   DAY_PART_02-Afternoon  DAY_PART_03-Early Evening  DAY_PART_04-Evening  
0                      1                          0                    0  
1                      0                          0                    1  
2                      0                          0                    0  
3                      1                          0                    0  
4                      0                          1                    0  

[5 rows x 32 columns]

In [101]:
df_data_model = np.array(DF_data)


In [102]:
df_data_model

array([[2.000e+00, 2.016e+03, 7.000e+00, ..., 1.000e+00, 0.000e+00,
        0.000e+00],
       [1.200e+01, 2.016e+03, 7.000e+00, ..., 0.000e+00, 0.000e+00,
        1.000e+00],
       [4.000e+00, 2.016e+03, 7.000e+00, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       ...,
       [7.000e-02, 2.018e+03, 1.100e+01, ..., 1.000e+00, 0.000e+00,
        0.000e+00],
       [7.000e-02, 2.018e+03, 1.100e+01, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       [7.000e-02, 2.018e+03, 1.100e+01, ..., 1.000e+00, 0.000e+00,
        0.000e+00]])

In [80]:
# list(df_data_model)

In [103]:


df_data_model.shape

X = df_data_model[:, 1:df_data_model.shape[1]]
y = df_data_model[:, 0]

In [104]:
X

array([[2.016e+03, 7.000e+00, 1.000e+00, ..., 1.000e+00, 0.000e+00,
        0.000e+00],
       [2.016e+03, 7.000e+00, 2.000e+00, ..., 0.000e+00, 0.000e+00,
        1.000e+00],
       [2.016e+03, 7.000e+00, 2.000e+00, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       ...,
       [2.018e+03, 1.100e+01, 1.000e+00, ..., 1.000e+00, 0.000e+00,
        0.000e+00],
       [2.018e+03, 1.100e+01, 1.000e+00, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       [2.018e+03, 1.100e+01, 1.000e+00, ..., 1.000e+00, 0.000e+00,
        0.000e+00]])

In [105]:
y

array([ 2.  , 12.  ,  4.  , ...,  0.07,  0.07,  0.07])

In [106]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=1)

In [107]:
X_train.shape

(19862, 31)

In [108]:
X_test.shape

(4966, 31)

In [109]:
X_train

array([[2.018e+03, 1.000e+00, 3.000e+01, ..., 1.000e+00, 0.000e+00,
        0.000e+00],
       [2.018e+03, 8.000e+00, 3.000e+00, ..., 0.000e+00, 1.000e+00,
        0.000e+00],
       [2.018e+03, 1.100e+01, 9.000e+00, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       ...,
       [2.018e+03, 3.000e+00, 7.000e+00, ..., 0.000e+00, 1.000e+00,
        0.000e+00],
       [2.017e+03, 1.000e+00, 5.000e+00, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       [2.016e+03, 8.000e+00, 1.000e+01, ..., 1.000e+00, 0.000e+00,
        0.000e+00]])

In [110]:
X_test


array([[2.017e+03, 2.000e+00, 1.100e+01, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       [2.018e+03, 2.000e+00, 6.000e+00, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       [2.018e+03, 3.000e+00, 1.000e+00, ..., 0.000e+00, 0.000e+00,
        1.000e+00],
       ...,
       [2.018e+03, 6.000e+00, 1.000e+01, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       [2.017e+03, 3.000e+00, 1.800e+01, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       [2.018e+03, 4.000e+00, 9.400e+01, ..., 0.000e+00, 0.000e+00,
        0.000e+00]])

In [111]:

# Import the model we are using
from sklearn.ensemble import RandomForestRegressor

In [112]:
# Instantiate model with 1000 decision trees
rf = RandomForestRegressor(n_estimators = 1000, random_state = 42)

In [113]:
# Train the model on training data
rf.fit(X_train, y_train);

In [114]:
# Use the forest's predict method on the test data
predictions = rf.predict(X_test)
# Calculate the absolute errors
errors = abs(predictions - y_test)
# Print out the mean absolute error (mae)
print('Mean Absolute Error:', round(np.mean(errors), 2), 'degrees.')


Mean Absolute Error: 0.64 degrees.


In [115]:
print(errors)

[0.00244 0.02198 0.      ... 0.08148 0.04034 0.46164]


In [116]:
# Calculate mean absolute percentage error (MAPE)
mape = 100 * (errors / y_test)
# Calculate and display accuracy
accuracy = 100 - np.mean(mape)
print('Accuracy:', round(accuracy, 2), '%.')

Accuracy: -inf %.


In [117]:
mape

array([0.00739394, 0.1256    , 0.        , ..., 0.22021622, 0.06895726,
       0.14382653])

In [118]:
accuracy

-inf

In [119]:
y_test

array([ 33.  ,  17.5 ,   2.5 , ...,  37.  ,  58.5 , 320.97])

In [120]:
predictions

array([ 33.00244,  17.52198,   2.5    , ...,  36.91852,  58.45966,
       320.50836])

In [123]:
np.mean(np.abs((y_test - predictions) )) 

0.6415442227144799

In [124]:

from sklearn.metrics import mean_squared_error
from math import sqrt

In [125]:
meanSquaredError=mean_squared_error(y_test, predictions)
print("MSE:", meanSquaredError)
rootMeanSquaredError = sqrt(meanSquaredError)
print("RMSE:", rootMeanSquaredError)

MSE: 12.678016214316038
RMSE: 3.5606202007959284


In [127]:
 mse = mean_squared_error(y_test, predictions)

In [128]:
mse

12.678016214316038